# ========================================
# EKS DEPLOYMENT MODULE VARIABLES
# ========================================

# ========================================
# COMMON VARIABLES (Generated by Terragrunt)
# ========================================
# These variables are provided by Terragrunt root configuration
variable "region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Project name"
  type        = string
}

variable "environment" {
  description = "Environment name"
  type        = string
}

variable "cluster_name" {
  description = "EKS cluster name"
  type        = string
}

variable "common_tags" {
  description = "Common tags for all resources"
  type        = map(string)
  default     = {}
}

# ========================================
# PROVIDER CONFIGURATION VARIABLES
# ========================================
# These variables are used by the generated providers.tf
variable "aws_region" {
  description = "AWS region for provider configuration"
  type        = string
  default     = "us-east-1"
}

variable "allowed_account_ids" {
  description = "List of allowed AWS account IDs"
  type        = list(string)
  default     = []
}

variable "owner" {
  description = "Owner tag for resources"
  type        = string
  default     = "platform-team"
}

variable "cost_center" {
  description = "Cost center tag for resources"
  type        = string
  default     = "Engineering"
}

# ========================================
# STAGE CONTROL VARIABLES
# ========================================
variable "enable_stage_01_vpc" {
  description = "Enable VPC discovery stage"
  type        = bool
  default     = true
}

variable "enable_stage_02_bastion" {
  description = "Enable bastion host stage"
  type        = bool
  default     = false
}

variable "enable_stage_02_cluster" {
  description = "Enable EKS cluster stage (sandbox naming)"
  type        = bool
  default     = false
}

variable "enable_stage_03_cluster" {
  description = "Enable EKS cluster stage (prod naming)"
  type        = bool
  default     = false
}

variable "enable_stage_03_nodes" {
  description = "Enable EKS node group stage (sandbox naming)"
  type        = bool
  default     = false
}

variable "enable_stage_04_nodes" {
  description = "Enable EKS node group stage (prod naming)"
  type        = bool
  default     = false
}

variable "enable_stage_04_addons" {
  description = "Enable EKS addons stage (sandbox naming)"
  type        = bool
  default     = false
}

variable "enable_stage_05_addons" {
  description = "Enable EKS addons stage (prod naming)"
  type        = bool
  default     = false
}

variable "enable_stage_05_monitoring" {
  description = "Enable monitoring stage (sandbox naming)"
  type        = bool
  default     = false
}

variable "enable_stage_06_monitoring" {
  description = "Enable monitoring stage (prod naming)"
  type        = bool
  default     = false
}

# ========================================
# VPC DISCOVERY VARIABLES
# ========================================
variable "vpc_id" {
  description = "VPC ID for EKS cluster (explicit ID has highest priority)"
  type        = string
  default     = ""
}

variable "vpc_name" {
  description = "VPC name for auto-discovery (used when vpc_id is empty)"
  type        = string
  default     = ""
}

variable "private_subnet_tags" {
  description = "Tag values to identify private subnets"
  type        = list(string)
  default     = ["Private"]
}

variable "public_subnet_tags" {
  description = "Tag values to identify public subnets"
  type        = list(string)
  default     = ["Public"]
}

variable "use_name_filter" {
  description = "Use name filter for subnet discovery"
  type        = bool
  default     = true
}

variable "validate_network" {
  description = "Validate network configuration"
  type        = bool
  default     = true
}

# ========================================
# BASTION HOST VARIABLES
# ========================================
variable "enable_bastion" {
  description = "Enable bastion host deployment"
  type        = bool
  default     = false
}

variable "bastion_create_new" {
  description = "Create new bastion instance"
  type        = bool
  default     = true
}

variable "bastion_create_eks_access_sg" {
  description = "Create EKS access security group for bastion"
  type        = bool
  default     = true
}

variable "bastion_create_ssm_documents" {
  description = "Create SSM documents for bastion management"
  type        = bool
  default     = true
}

variable "bastion_os" {
  description = "Bastion host operating system"
  type        = string
  default     = "amazon-linux"
}

variable "bastion_ami" {
  description = "Bastion host AMI ID"
  type        = string
  default     = ""
}

variable "bastion_instance_type" {
  description = "Bastion host instance type"
  type        = string
  default     = "t3.micro"
}

variable "bastion_key_pair_name" {
  description = "EC2 key pair name for bastion host"
  type        = string
  default     = ""
}

variable "bastion_vpc_cidr" {
  description = "VPC CIDR for bastion security group rules"
  type        = string
  default     = "10.0.0.0/16"
}

variable "bastion_subnet_id" {
  description = "Subnet ID for bastion host"
  type        = string
  default     = ""
}

variable "bastion_availability_zone" {
  description = "Availability zone for bastion host"
  type        = string
  default     = ""
}

variable "bastion_allowed_cidr_blocks" {
  description = "CIDR blocks allowed to access bastion host"
  type        = list(string)
  default     = ["0.0.0.0/0"]
}

variable "bastion_ssh_port" {
  description = "SSH port for bastion host"
  type        = number
  default     = 22
}

variable "bastion_kubectl_version" {
  description = "kubectl version for bastion host"
  type        = string
  default     = "1.30.0"
}

# ========================================
# EKS CLUSTER VARIABLES
# ========================================
variable "cluster_version" {
  description = "EKS cluster version"
  type        = string
  default     = "1.30"
}

variable "endpoint_private_access" {
  description = "Enable private API server endpoint"
  type        = bool
  default     = true
}

variable "endpoint_public_access" {
  description = "Enable public API server endpoint"
  type        = bool
  default     = false
}

variable "public_access_cidrs" {
  description = "CIDR blocks for public API server access"
  type        = list(string)
  default     = ["0.0.0.0/0"]
}

variable "eks_create_private_access_sg" {
  description = "Create private access security group for EKS"
  type        = bool
  default     = false
}

variable "eks_private_access_cidrs" {
  description = "CIDR blocks for EKS private access"
  type        = list(string)
  default     = []
}

variable "eks_additional_security_group_ids" {
  description = "Additional security group IDs for EKS cluster"
  type        = list(string)
  default     = []
}

variable "enable_cluster_encryption" {
  description = "Enable EKS cluster encryption"
  type        = bool
  default     = false
}

variable "kms_key_arn" {
  description = "KMS key ARN for cluster encryption (explicit ARN has highest priority)"
  type        = string
  default     = ""
}

variable "kms_key_alias" {
  description = "KMS key alias for auto-discovery (used when kms_key_arn is empty)"
  type        = string
  default     = ""
}

# ========================================
# NODE GROUP VARIABLES
# ========================================
variable "node_instance_types_general" {
  description = "Instance types for general node group"
  type        = list(string)
  default     = ["t3.medium"]
}

variable "node_desired_size_general" {
  description = "Desired size for general node group"
  type        = number
  default     = 2
}

variable "node_min_size_general" {
  description = "Minimum size for general node group"
  type        = number
  default     = 1
}

variable "node_max_size_general" {
  description = "Maximum size for general node group"
  type        = number
  default     = 4
}

variable "capacity_type" {
  description = "Capacity type for node group (ON_DEMAND or SPOT)"
  type        = string
  default     = "ON_DEMAND"
}

variable "disk_size" {
  description = "EBS disk size for worker nodes (GB)"
  type        = number
  default     = 50
}

# ========================================
# EKS ADDONS VARIABLES
# ========================================
variable "enable_vpc_cni" {
  description = "Enable VPC CNI addon"
  type        = bool
  default     = true
}

variable "enable_coredns" {
  description = "Enable CoreDNS addon"
  type        = bool
  default     = true
}

variable "enable_kube_proxy" {
  description = "Enable kube-proxy addon"
  type        = bool
  default     = true
}

variable "enable_ebs_csi_driver" {
  description = "Enable EBS CSI driver addon"
  type        = bool
  default     = true
}

variable "create_irsa_roles" {
  description = "Create IAM roles for service accounts"
  type        = bool
  default     = false
}

variable "oidc_provider_arn" {
  description = "OIDC provider ARN for IRSA (from EKS cluster)"
  type        = string
  default     = null
}

# ========================================
# MONITORING VARIABLES
# ========================================
variable "monitoring_namespace" {
  description = "Kubernetes namespace for monitoring stack"
  type        = string
  default     = "monitoring"
}

variable "enable_prometheus" {
  description = "Enable Prometheus monitoring"
  type        = bool
  default     = true
}

variable "grafana_admin_password" {
  description = "Grafana admin password"
  type        = string
  default     = "admin"
  sensitive   = true
}

variable "enable_kong" {
  description = "Enable Kong API gateway"
  type        = bool
  default     = false
}

variable "kong_proxy_service_type" {
  description = "Kong proxy service type"
  type        = string
  default     = "LoadBalancer"
}

variable "kong_admin_service_type" {
  description = "Kong admin service type"
  type        = string
  default     = "ClusterIP"
}

variable "prometheus_storage_size" {
  description = "Prometheus storage size"
  type        = string
  default     = "50Gi"
}

variable "grafana_storage_size" {
  description = "Grafana storage size"
  type        = string
  default     = "10Gi"
}

variable "grafana_ingress_enabled" {
  description = "Enable Grafana ingress"
  type        = bool
  default     = false
}

variable "grafana_ingress_host" {
  description = "Grafana ingress host"
  type        = string
  default     = "grafana.local"
}
